<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="squery" nsURI="http://www.teco.edu/squery" nsPrefix="squery">
  <eClassifiers xsi:type="ecore:EClass" name="QueryModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="automata" ordered="false" eType="//Automata" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" ordered="false" upperBound="-1" eType="//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Automata">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" ordered="false" eType="//Query" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false" eType="//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="st" ordered="false" eType="//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" ordered="false" upperBound="-1" eType="//BoolExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op2" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" ordered="false" eType="//Operand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op1" ordered="false" eType="//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" ordered="false" unique="false" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="platform:/resource/edu.teco.automata/model/Automata.ecore#//SimpleState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
