CPPFLAGS=-I../../edu.teco.dpws.generator/shared/include -I../../SensorValuesService/src-gen
LDFLAGS=-L../../SensorValuesService/Debug -L ../../edu.teco.decenc/bitsio 
LDLIBS=-lbitsio_buf -lSensorValuesService -lparticle
CFLAGS=-O0 -g
