set(CTEST_PROJECT_NAME "WS4D-gSOAP")
set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "139.30.201.146:8082")
set(CTEST_DROP_LOCATION "/submit.php?project=WS4D-gSOAP")
set(CTEST_DROP_SITE_CDASH TRUE)
