<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TimedTrigger"
    nsURI="http://aletheia-project.de/iot/TimedTrigger/1.0" nsPrefix="tt">
  <eClassifiers xsi:type="ecore:EClass" name="TimedTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="if not set->now&#xD;&#xA;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dutycycle" eType="#//DutyCycle"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repetition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Short">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="if not set -> infinity or out of memory"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sleep" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DutyCycle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Duration">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repeat" eType="#//Repetition"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedTriggerService" abstract="true"
      interface="true">
    <eOperations name="createTrigger" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Byte">
      <eParameters name="trigger" eType="#//TimedTrigger"/>
    </eOperations>
    <eOperations name="deleteTrigger">
      <eParameters name="triggerId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Byte"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedTriggerRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompareTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="ecore:EClass addressing.ecore#//AttributedURI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hysteresis" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="holdoff" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Action" lowerBound="1"
        eType="ecore:EClass addressing.ecore#//AttributedURI" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="namespace" value="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PinTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Byte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="holdoff" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="up"/>
    <eLiterals name="down" value="1"/>
    <eLiterals name="both" value="2"/>
  </eClassifiers>
</ecore:EPackage>
